#Allows the plugin to start even if it may not be compatible with the current server version. This can lead to unexpected bugs and should only be used in a testing environment.
allow-unsupported-versions: false

#Filter specific settings
filters:
  #Prevents players from seeing their own saturation value.
  saturation:
    enabled: true

  #Can make world seed cracking harder (not impossible). Will slightly alter biome coloring.
  worldseed:
    enabled: false

  #Can make enchantment seed cracking harder (not impossible). Will slightly alter the galactic alphabet text in the enchanting table menu. (That text is useless anyways.)
  enchantseed:
    enabled: true

  #Options for filtering data in entity metadata packets.
  entitydata:
    #This will toggle all entity data filters at once.
    enabled: true

    #Hides the oxygen amount of other entities.
    airticks: 
      enabled: false

    #Hides the health of other entities.
    health: 
      enabled: true

      #Don't filter the health of the vehicle the player is riding. (The health bar of the current vehicle is visible in vanilla.)
      ignore-vehicles: true

      #Don't filter the health of tamed dogs. It's needed to display the tail position, which can be used to determine the dogs health in vanilla.
      ignore-tamed-dogs: true

      #Don't filter the health of ender dragons. Filtering their health will break their death animation in 1.15+.
      #Doesn't affect the bossbar.
      ignore-enderdragon: true

      #Don't filter the health of withers. Filtering their health will break the shine effect when their health is less than 50% of their max health.
      #Doesn't affect the bossbar.
      ignore-wither: true

      #This fixes being unable to see the cracks on iron golems when they lose health on 1.15+ servers.
      #To achieve this, the health is sent in steps of 25, which is when the golem cracks, so health indicators don't provide more information than in vanilla.
      show-irongolem-cracks: true

    #Hides the xp level of other players.
    xp: 
      enabled: true